name: 'cloud-assignment-2-cloud-native-app'

version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'

  flask:
    image: flask-app:latest
    ports:
      - '3000:5000'
    depends_on:
      - mongo
  
volumes:
  data: