apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m

      routes:
        - match:
            alertname: TargetDown
          receiver: 'slack-notifications'

    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - channel: '#assignment-2-sak9791'
            send_resolved: true
            title: "Kubernetes Alert: {{ .CommonAnnotations.summary }}"
            text: "{{ .CommonAnnotations.description }}"

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['namespace', 'alertname']
